name: Daily ETF Analysis Update

on:
  schedule:
    # Run daily at 6am UTC
    - cron: '0 6 * * 1-5'  # Monday-Friday at 6am UTC (weekdays only)
  workflow_dispatch:  # Allow manual triggers

permissions:
  contents: write  # Allow the action to push commits
  actions: read    # Allow reading workflow information

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0  # Fetch full history for git operations
        
    - name: Create and switch to data-updates branch
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        # Create or switch to data-updates branch
        git checkout -B data-updates
        git reset --hard origin/main  # Ensure it's based on latest main
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run ETF analysis
      id: analysis
      continue-on-error: true
      run: |
        echo "Starting ETF analysis..."
        python multi_ticker_orchestrator.py || echo "Analysis completed with warnings"
        echo "Analysis step completed"
        
    - name: Generate web data with risk integration
      id: webdata  
      continue-on-error: true
      run: |
        echo "Generating web data with automatic risk assessment..."
        python scripts/generate_web_data.py || echo "Web data generation completed with warnings"
        echo "Web data generation completed with risk assessment integration"
        
    - name: Check if files were created
      run: |
        echo "Checking for generated web data files..."
        ls -la yast-react/public/data/ || echo "No web data directory found"
        echo "Analysis completed. Text files are in local directory but not committed (ignored by .gitignore)"
        
    - name: Commit and push data updates to separate branch
      run: |
        git config --local advice.addIgnoredFile false
        
        # Add web data files (these are the important ones for Netlify)
        find yast-react/public/data -name "*.json" -exec git add {} \; 2>/dev/null || echo "No JSON files to add"
        
        # Check if there are any changes
        if git diff --staged --quiet; then
          echo "No changes to commit"
          exit 0
        else
          echo "Changes detected, committing to data-updates branch..."
          git commit -m "Daily ETF data update $(date +%Y-%m-%d)" || echo "Commit failed"
          git push -f origin data-updates || echo "Push to data-updates failed"
        fi
        
    - name: Merge data-updates into main
      run: |
        # Switch back to main and merge the data updates
        git checkout main
        git pull origin main  # Get latest main
        git merge data-updates -m "Auto-merge daily data updates $(date +%Y-%m-%d)" || echo "Merge failed"
        git push origin main || echo "Push to main failed"
        
    - name: Trigger Netlify deploy
      if: success()
      continue-on-error: true
      run: |
        if [ -n "${{ secrets.NETLIFY_BUILD_HOOK }}" ]; then
          echo "Triggering Netlify deployment..."
          curl -X POST -d {} "${{ secrets.NETLIFY_BUILD_HOOK }}" || echo "Netlify trigger failed"
        else
          echo "No Netlify build hook configured"
        fi
