name: Daily ETF Analysis Update

on:
  schedule:
    # Run daily at 6am UTC
    - cron: '0 6 * * 1-5'  # Monday-Friday at 6am UTC (weekdays only)
  workflow_dispatch:  # Allow manual triggers

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run ETF analysis
      id: analysis
      continue-on-error: true
      run: |
        echo "Starting ETF analysis..."
        python multi_ticker_orchestrator.py || echo "Analysis completed with warnings"
        echo "Analysis step completed"
        
    - name: Generate web data
      id: webdata  
      continue-on-error: true
      run: |
        echo "Generating web data..."
        python scripts/generate_web_data.py || echo "Web data generation completed with warnings"
        echo "Web data generation completed"
        
    - name: Check if files were created
      run: |
        echo "Checking for generated files..."
        ls -la yast-react/public/data/ || echo "No web data directory found"
        ls -la data/*.csv | head -10 || echo "No CSV files found"
        ls -la comprehensive_sorted_table_*.txt | head -5 || echo "No comprehensive table files found"
        
    - name: Commit and push if data changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git config --local advice.addIgnoredFile false
        
        # Only add files that are NOT ignored by .gitignore
        # Add web data files (these are explicitly not ignored)
        find yast-react/public/data -name "*.json" -exec git add {} \; 2>/dev/null || echo "No JSON files to add"
        
        # Add analysis output files (if they exist and aren't ignored)
        find . -maxdepth 1 -name "comprehensive_sorted_table_*.txt" -exec git add {} \; 2>/dev/null || echo "No table files to add"
        find . -maxdepth 1 -name "multi_ticker_analysis_*.txt" -exec git add {} \; 2>/dev/null || echo "No analysis files to add"
        
        # Don't try to add data/*.csv files as they are ignored by .gitignore
        
        # Check if there are any changes
        if git diff --staged --quiet; then
          echo "No changes to commit"
          exit 0
        else
          echo "Changes detected, committing..."
          git commit -m "Daily ETF data update $(date +%Y-%m-%d)" || echo "Commit failed"
          git push || echo "Push failed"
        fi
        
    - name: Trigger Netlify deploy
      if: success()
      continue-on-error: true
      run: |
        if [ -n "${{ secrets.NETLIFY_BUILD_HOOK }}" ]; then
          echo "Triggering Netlify deployment..."
          curl -X POST -d {} "${{ secrets.NETLIFY_BUILD_HOOK }}" || echo "Netlify trigger failed"
        else
          echo "No Netlify build hook configured"
        fi
